globalcorp-quotesapiapiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ordersapiowner
  description: ordersapi owner
spec:
  type: business-unit
  profile:
    displayName: ordersapi Team
  children:
    - other

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ui
  description: |
    API to store customer storefront orders.
  links:
    - title: Website
      url: http://harness.io
  annotations:
    harness.io/pipelines: |
      Build and Deploy: https://app.harness.io/ng/account/IFG41DWvSnaRLOVNB2uesg/module/cd/orgs/default/projects/globalcorp/pipelines/GoodApi/pipeline-studio?storeType=INLINE

  tags:
    - globalcorp
spec:
  type: service
  owner: ordersapiowner
  lifecycle: experimental
