apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: deployapi
  title: Create and deploy new API
  description: Create and deploy new API 
spec:
  owner: service.owner
  type: service
  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Name of the new API
      required:
        - api_name
        - api_type
      properties:
        api_name:
          title: Api Name
          type: string
          description: Api Name
        api_type:
          title: Api Type
          type: string
          description: Api Type
          default: expedited
          enum:
            - standard
            - expedited
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken       
  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: trigger
      name: Create and deploy API
      action: trigger:harness-custom-pipeline
      input:
        url: https://app.harness.io/ng/account/EeRjnXTnS4GrLG5VNNJZUw/module/cd/orgs/sandbox/projects/ShawnPearson/pipelines/IDPcustom/pipeline-studio?storeType=INLINE
        inputset:
          api_name: ${{ parameters.api_name }}
          api_type: ${{ parameters.api_type }}
        apikey: ${{ parameters.token }}
    # The final step is to register our new component in the catalog.

  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
